ALTER TABLE shops ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE shops ALTER COLUMN created_at SET DEFAULT current_timestamp;
ALTER TABLE shops ALTER COLUMN is_deleted SET DEFAULT 0;

ALTER TABLE items ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE items ALTER COLUMN created_at SET DEFAULT current_timestamp;
ALTER TABLE items ALTER COLUMN deadline_date SET NOT NULL;
ALTER TABLE items ALTER COLUMN is_deleted SET DEFAULT 0;

ALTER TABLE users ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT current_timestamp;
ALTER TABLE users ALTER COLUMN is_deleted SET DEFAULT 0;
ALTER TABLE users ALTER COLUMN email SET NOT NULL;
ALTER TABLE users ALTER COLUMN password SET NOT NULL;
ALTER TABLE users ALTER COLUMN birthdate SET NOT NULL;

ALTER TABLE items_users ALTER COLUMN item_id TYPE BIGINT;
ALTER TABLE items_users ALTER COLUMN user_id TYPE BIGINT;

ALTER TABLE shop_items ALTER COLUMN item_id TYPE BIGINT;
ALTER TABLE shop_items ALTER COLUMN shop_id TYPE BIGINT;
